-- Carga inicial de datos PLV desde petPLV.xlsx (hoja cargaIni)
-- Idempotente: usa ON CONFLICT DO NOTHING en los maestros y
-- comprueba existencia antes de cada articulo. Re-ejecutable sin
-- duplicar ni romper datos previos.

-- Empresas
INSERT INTO plv_companies (code, name) VALUES ('Y', 'Ayestaran') ON CONFLICT (code) DO NOTHING;
INSERT INTO plv_companies (code, name) VALUES ('N', 'Nord Pirineus') ON CONFLICT (code) DO NOTHING;
INSERT INTO plv_companies (code, name) VALUES ('Z', 'Zubillaga') ON CONFLICT (code) DO NOTHING;

-- Grupos
INSERT INTO plv_groups (code, name, sort_order) VALUES ('EST', 'ESTABLECIMIENTO', 1) ON CONFLICT (code) DO NOTHING;
INSERT INTO plv_groups (code, name, sort_order) VALUES ('EVT', 'EVENTOS', 2) ON CONFLICT (code) DO NOTHING;

-- Marcas
INSERT INTO plv_brands (code, name) VALUES ('SM', 'SAN MIGUEL') ON CONFLICT (code) DO NOTHING;
INSERT INTO plv_brands (code, name) VALUES ('ALH', 'ALHAMBRA') ON CONFLICT (code) DO NOTHING;
INSERT INTO plv_brands (code, name) VALUES ('LSV', 'LA SALVE') ON CONFLICT (code) DO NOTHING;
INSERT INTO plv_brands (code, name) VALUES ('STL', 'STELLA') ON CONFLICT (code) DO NOTHING;
INSERT INTO plv_brands (code, name) VALUES ('MAG', 'MAGNA') ON CONFLICT (code) DO NOTHING;
INSERT INTO plv_brands (code, name) VALUES ('MSM', 'MSM') ON CONFLICT (code) DO NOTHING;
INSERT INTO plv_brands (code, name) VALUES ('MAH', 'MAHOU') ON CONFLICT (code) DO NOTHING;

-- Articulos (idempotencia por UNIQUE(company_id, code))
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7151', 'MESA SAN MIGUEL COBERTURA 2022' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7152', 'SILLA SAN MIGUEL COBERTURA 2022' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7833', 'MESA S. MIGUEL COBERTURA VERDE 2025' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7832', 'SILLA S. MIGUEL COBERTURA VERDE 2025' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '1900', 'MESA ALHAMBRA COBERTURA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '2369', 'SILLA ALHAMBRA COBERTURA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1893', 'MESA LA SALVE PLASTICO NEGRA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1894', 'SILLA LA SALVE PLASTICO NEGRA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '7183', 'MESA LA SALVE PLASTICO BLANCA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '7184', 'SILLA LA SALVE PLASTICO BLANCA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1898', 'MESA LA SALVE ALTA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'STL'), '7122', 'MESA STELLA ARTOIS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'STL'), '7123', 'SILLA STELLA ARTOIS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1897', 'TABURETE LA SALVE ALTO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '1873', 'PARASOL 2,5 M SM LP 2020' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '1895', 'PARASOL 2,5 M ALH LP 2017' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1896', 'PARASOL 2,5 M LA SALVE' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MAG'), '7132', 'PARASOL 2,5 M SM MAGNA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MSM'), '1890', 'BASE PARASOL 2,5 GRIS GEN' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '1867', 'BOTELLERO 1 METRO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '4157', 'BOTELLERO 1,5 METROS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '1881', 'MOSTRADOR METÁLICO SM' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '6008', 'BOTELLERO EVENTOS 1 METRO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '6009', 'BOTELLERO EVENTOS 1,5 METROS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '5556', 'PARASOL EVENTOS 2,5M' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '1903', 'MESA EVENTOS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Y'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '1904', 'SILLA EVENTOS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7151', 'MESA SAN MIGUEL COBERTURA 2022' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7152', 'SILLA SAN MIGUEL COBERTURA 2022' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '1879', 'MESA SAN MIGUEL ALTA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '1880', 'TABURETE SAN MIGUEL ALTO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '1900', 'MESA ALHAMBRA COBERTURA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '2369', 'SILLA ALHAMBRA COBERTURA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '7663', 'MESA ALHAMBRA ALTA 2024' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '7664', 'TABURETE ALHAMBRA 2024' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MAH'), '3859', 'MESA MAHOU COBERTURA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MAH'), '3856', 'SILLA MAHOU COBERTURA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MAH'), '7582', 'MESA MAHOU ALTA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MAH'), '7583', 'TABURETE MAHOU ALTA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '1873', 'PARASOL 2,5 M SM LP 2020' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '1895', 'PARASOL 2,5 M ALH LP 2017' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MAG'), '7132', 'PARASOL 2,5 M SM MAGNA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MAH'), '7494', 'PARASOL MAHOU 2,5 M' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MSM'), '1890', 'BASE PARASOL 2,5 GRIS GEN' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '1867', 'BOTELLERO 1 METRO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '4157', 'BOTELLERO 1,5 METROS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '1881', 'MOSTRADOR METÁLICO EVENTOS 1,80M' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '6008', 'BOTELLERO EVENTOS 1 METRO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '6009', 'BOTELLERO EVENTOS 1,5 METROS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '5556', 'PARASOL EVENTOS 2,5M' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '1903', 'MESA EVENTOS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'N'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '1904', 'SILLA EVENTOS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7151', 'MESA SAN MIGUEL COBERTURA 2022' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7152', 'SILLA SAN MIGUEL COBERTURA 2022' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7833', 'MESA S. MIGUEL COBERTURA VERDE 2025' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '7832', 'SILLA S. MIGUEL COBERTURA VERDE 2025' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '1900', 'MESA ALHAMBRA COBERTURA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '2369', 'SILLA ALHAMBRA COBERTURA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1893', 'MESA LA SALVE PLASTICO NEGRA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1894', 'SILLA LA SALVE PLASTICO NEGRA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '7183', 'MESA LA SALVE PLASTICO BLANCA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '7184', 'SILLA LA SALVE PLASTICO BLANCA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '7621', 'MESA LA SALVE PLASTICO GRIS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '7622', 'SILLA LA SALVE PLASTICO GRIS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'STL'), '7122', 'MESA STELLA ARTOIS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'STL'), '7123', 'SILLA STELLA ARTOIS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '3974', 'MESA MADERA LA SALVE' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '3975', 'SILLA MADERA LA SALVE' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '1879', 'MESA SAN MIGUEL ALTA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '1880', 'TABURETE SAN MIGUEL ALTO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1898', 'MESA LA SALVE ALTA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1897', 'TABURETE LA SALVE ALTO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'STL'), '7819', 'MESA STELLA ARTOIS ALTA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'STL'), '7818', 'TABURETE STELLA ARTOIS ALTO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'SM'), '1873', 'PARASOL 2,5 M SM LP 2020' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'ALH'), '1895', 'PARASOL 2,5 M ALH LP 2017' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'LSV'), '1896', 'PARASOL 2,5 M LA SALVE' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MAG'), '7132', 'PARASOL 2,5 M SM MAGNA' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'STL'), '7630', 'PARASOL 2,5M STELLA ARTOIS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MSM'), '1890', 'BASE PARASOL 2,5 GRIS GEN' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MSM'), '6868', 'BASE PARASOL CON RUEDAS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MSM'), '1867', 'BOTELLERO 1 METRO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EST'), (SELECT id FROM plv_brands WHERE code = 'MSM'), '4157', 'BOTELLERO 1,5 METROS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '1881', 'MOSTRADOR METÁLICO SM' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '6008', 'BOTELLERO EVENTOS 1 METRO' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '6009', 'BOTELLERO EVENTOS 1,5 METROS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '5556', 'PARASOL EVENTOS 2,5M' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '1903', 'MESA EVENTOS' ON CONFLICT (company_id, code) DO NOTHING;
INSERT INTO plv_articles (company_id, group_id, brand_id, code, description) SELECT (SELECT id FROM plv_companies WHERE code = 'Z'), (SELECT id FROM plv_groups WHERE code = 'EVT'), NULL, '1904', 'SILLA EVENTOS' ON CONFLICT (company_id, code) DO NOTHING;
